"""New fields in user model

Revision ID: ab40c1bbe7b5
Revises: dcedaecbec88
Create Date: 2020-06-12 09:42:51.289213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab40c1bbe7b5'
down_revision = 'dcedaecbec88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_has')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_has', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
