"""New fields in user model

Revision ID: d136b6023298
Revises: ab40c1bbe7b5
Create Date: 2020-06-12 09:52:11.793970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd136b6023298'
down_revision = 'ab40c1bbe7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_has')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_has', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
